### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'instance_heartbeat_interval' in 'field list' [file: /usr/share/centreon/www/class/centreonDBStatement.class.php] [line: 111] )

### ISSUE THREAD

**Issue by Phoenixoboros** [centreon/centreon-engine#452]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
centreon-20.10.4-1.el7.centos.noarch
centreon-auto-discovery-server-20.10.2-1.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.4-1.el7.centos.noarch
centreon-broker-20.10.4-1.el7.centos.x86_64
centreon-broker-cbd-20.10.4-1.el7.centos.x86_64
centreon-broker-cbmod-20.10.4-1.el7.centos.x86_64
centreon-broker-core-20.10.4-1.el7.centos.x86_64
centreon-broker-storage-20.10.4-1.el7.centos.x86_64
centreon-clib-20.10.1-1.el7.centos.x86_64
centreon-common-20.10.4-1.el7.centos.noarch
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-cwrapper-perl-0.1-1.el7.centos.x86_64
centreon-database-20.10.4-1.el7.centos.noarch
centreon-engine-20.10.3-6.el7.centos.x86_64
centreon-engine-daemon-20.10.3-6.el7.centos.x86_64
centreon-engine-extcommands-20.10.3-6.el7.centos.x86_64
centreon-gorgone-20.10.3-1.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.3-1.el7.centos.noarch
centreon-license-manager-20.10.2-1.el7.centos.noarch
centreon-license-manager-common-20.10.2-1.el7.centos.noarch
centreon-perl-libs-20.10.4-1.el7.centos.noarch
centreon-plugin-Applications-Antivirus-Kaspersky-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Backup-Emc-Recoverypoint-Ssh-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Biztalk-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Clamav-Ssh-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Databases-Elasticsearch-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Databases-Firebird-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Databases-Informix-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Databases-Mssql-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Databases-Oracle-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Databases-Postgresql-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Databases-Sap-Hana-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Databases-Sybase-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Docker-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Github-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Haproxy-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Hibernate-Jmx-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-IBM-Tsm-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Jboss-Jmx-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Jenkins-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Lmsensors-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Lync-2013-Mssql-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Mail-Bluemind-20200410-101650.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Pacemaker-Ssh-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Peoplesoft-Jmx-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Php-Apc-Web-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Php-Fpm-Web-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Bgp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Bgp-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dhcp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Imap-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Jmx-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Modbus-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ntp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ospf-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Radius-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Smtp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ssh-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Tcp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Telnet-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-Udp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Protocol-X509-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Redis-Cli-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Redis-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Selenium-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Sendmail-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Solr-Jmx-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-TrendMicro-Iwsva-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Video-Openheadend-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Video-Zixi-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Voip-Asterisk-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Voip-Asterisk-Ami-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Voip-Asterisk-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Vtom-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Weblogic-Jmx-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Webservers-Apache-Serverstatus-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Webservers-Nginx-Serverstatus-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Webservers-Tomcat-Jmx-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Webservers-Tomcat-Webmanager-20210113-100416.el7.centos.noarch
centreon-plugin-Applications-Zookeeper-Jmx-20210113-100416.el7.centos.noarch
centreon-plugin-Cloud-Aws-Billing-Api-20210113-100416.el7.centos.noarch
centreon-plugin-Cloud-Aws-Cloudfront-Api-20210113-100416.el7.centos.noarch
centreon-plugin-Cloud-Aws-Cloudwatch-Api-20210113-100416.el7.centos.noarch
centreon-plugin-Cloud-Aws-Ec2-Api-20210113-100416.el7.centos.noarch
centreon-plugin-Cloud-Aws-Elasticache-Api-20210113-100416.el7.centos.noarch
centreon-plugin-Cloud-Aws-Elb-Api-20210113-100416.el7.centos.noarch
centreon-plugin-Cloud-Aws-Lambda-Api-20210113-100416.el7.centos.noarch
centreon-plugin-Cloud-Aws-Rds-Api-20210113-100416.el7.centos.noarch
centreon-plugin-Cloud-Aws-S3-Api-20210113-100416.el7.centos.noarch
centreon-plugin-Cloud-Ovh-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Discovery-Nmap-20181019-1.el7.noarch
centreon-plugin-Hardware-Ats-Apc-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Dell-TL2000-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Device-Safenet-Keysecure-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Devices-Gorgy-Ntpserver-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Kvm-Avocent-Acs-6000-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Pdu-Apc-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Pdu-Clever-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Pdu-Emerson-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Pdu-Raritan-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Akcp-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Hwgste-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Jacarta-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Netbotz-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Sensorip-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Sensormetrix-Em01-Web-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Serverscheck-Sensorgateway-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Cisco-Ucs-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Dell-Cmc-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Dell-IDrac-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Dell-Openmanage-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Hp-Blade-Chassis-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Hp-Ilo-Xmlapi-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Hp-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Ibm-Bladecenter-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-servers-ibm-imm-snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Sun-Mgmtcards-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Sun-Mseries-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Sun-Sfxxk-Pssh-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Servers-Supermicro-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Dell-Compellent-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Dell-Equallogic-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Dell-Fluidfs-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Dell-Md3000-Smcli-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Dell-Ml6000-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Celerra-Ssh-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Clariion-Navisphere-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Datadomain-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Isilon-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Vplex-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Xtremio-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Exagrid-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Fujitsu-Eternus-Dx-Ssh-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hitachi-Hnas-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hitachi-Standard-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-3par-7000-Ssh-20190704-123459.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Eva-Cli-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Lefthand-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Msa2000-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Msl-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-P2000-Xmlapi-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Storeonce-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Storeonce-Ssh-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ds3000-Smcli-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ds4000-Smcli-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ds5000-Smcli-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Fs900-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Storwize-Ssh-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ts2900-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ts3100-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ts3200-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ts3500-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Lenovo-Sseries-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Netapp-Restapi-20200410-101650.el7.centos.noarch
centreon-plugin-Hardware-Storage-Netapp-Snmp-20200410-101650.el7.centos.noarch
centreon-plugin-Hardware-Storage-Nimble-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Oracle-Zs-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Overland-Neo-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Panzura-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Qnap-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Qsan-Nas-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Quantum-Scalar-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Storagetek-Sl-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Synology-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Storage-Violin-3000-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Telephony-Alcatel-OXE-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Ups-Apc-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Ups-Mge-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Ups-Powerware-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-3com-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Acmepacket-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Aerohive-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Audiocodes-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Beeware-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Cisco-Ironport-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Cisco-Meraki-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Cisco-Prime-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Cisco-Voice-Gateway-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Cisco-Waas-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Cisco-Wlc-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Citrix-Appacceleration-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Citrix-Sdx-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Cyberoam-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Dell-6200-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Dell-N4000-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Dell-Sseries-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Digi-AnywhereUSB-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Digi-Portserverts-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Digi-Sarian-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Dlink-Dgs3100-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Dlink-Standard-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Efficientip-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Evertz-FC7800-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Extreme-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Firewalls-Arkoon-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Firewalls-Checkpoint-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Firewalls-Cisco-Asa-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Firewalls-Fortinet-Fortigate-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Firewalls-Juniper-Sa-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Firewalls-Juniper-Srx-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Firewalls-Juniper-Ssg-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Firewalls-Paloalto-Standard-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Firewalls-Pfsense-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Firewalls-Stonesoft-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Fortinet-Fortimanager-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Freebox-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Fritzbox-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Fritzbox-Snmp-20171013-1.el7.noarch
centreon-plugin-Network-Generic-Bluecoat-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-H3c-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Hp-Vc-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Huawei-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Juniper-Ggsn-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Juniper-Isg-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Juniper-Mag-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Juniper-Trapeze-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Loadbalancers-A10-AX-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Loadbalancers-F5-Bigip-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Loadbalancers-Kemp-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Loadbalancers-Netscaler-Mpx8000-Snmp-20170120-1.el7.noarch
centreon-plugin-Network-Loadbalancers-Netscaler-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Netasq-Snmp-20170807-1.el7.noarch
centreon-plugin-Network-Netasq-Ssh-20170811-1.el7.noarch
centreon-plugin-Network-Netgear-Mseries-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Nokia-Timos-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Nortel-Standard-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Oneaccess-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Oracle-Infiniband-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Oracle-Otd-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Polycom-Rmx-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Radware-Alteon-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Raisecom-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Riverbed-Steelhead-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Routers-Atrica-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Routers-Juniper-Mseries-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Routers-Redback-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Ruckus-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Ruggedcom-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Sonus-SBC-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Sophos-Es-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Stormshield-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Stormshield-Ssh-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Switchs-Alcatel-Omniswitch-6850-20170329-1.el7.noarch
centreon-plugin-Network-Switchs-Alcatel-Omniswitch-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Switchs-Aruba-Standard-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Switchs-Brocade-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Switchs-Cisco-Smallbusiness-Standard-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Switchs-Hirschmann-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Switchs-Hp-Procurve-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Switchs-Juniper-Ex-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Ucopia-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Watchguard-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Network-Zyxel-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Notification-Highsms-20210113-100416.el7.centos.noarch
centreon-plugin-Operatingsystems-Aix-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Operatingsystems-Freebsd-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Operatingsystems-Hpux-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Operatingsystems-Solaris-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Restapi-20210113-100416.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20210113-100416.el7.centos.noarch
centreon-plugins-base-1.18-2.el7.centos.noarch
centreon-plugin-Virtualization-Nutanix-Snmp-20210113-100416.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20210113-100416.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Esx-Wsman-20210113-100416.el7.centos.noarch
centreon-plugin-Virtualization-VMWare-daemon-3.2.1-20201103101237.el7.centos.noarch
centreon-poller-centreon-engine-20.10.4-1.el7.centos.noarch
centreon-pp-manager-20.10.0-1.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.4-1.el7.centos.noarch
centreon-web-20.10.4-1.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch
```

***Operating System***

*CentOS Linux release 7.9.2009 (Core)*

***How the the component has been installed and versions***

- [X] *from packages*

Version: --

KVM

### Description

Comming from 20.10.2, updated to 20.10.4, now I have this error when reload poller:

```
Preparing environment... OK
Generating files... NOK (Exception received : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'instance_heartbeat_interval' in 'field list' [file: /usr/share/centreon/www/class/centreonDBStatement.class.php] [line: 111] )
Aborted.
```

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Configuration  >  Pollers  >  Export configuration

2. Check:
  Generate Configuration Files
  Run monitoring engine debug (-v)
  Move Export Files
  Restart Monitoring Engine	Method = Reload

### Describe the received result

```
Preparing environment... OK
Generating files... NOK (Exception received : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'instance_heartbeat_interval' in 'field list' [file: /usr/share/centreon/www/class/centreonDBStatement.class.php] [line: 111] )
Aborted.
```

### Describe the expected result

Everything OK

### Logs

/var/opt/rh/rh-php72/log/php-fpm/centreon-error.log

```
[10-Feb-2021 02:34:10 Europe/Paris] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'postpone_notification_to_timeperiod' in 'field list' in /usr/share/centreon/www/class/centreonDB.class.php:275
Stack trace:
#0 /usr/share/centreon/www/include/configuration/configNagios/DB-Func.php(2253): CentreonDB->query('UPDATE cfg_nagi...')
#1 /usr/share/centreon/www/include/configuration/configNagios/DB-Func.php(210): updateNagios('1')
#2 /usr/share/centreon/www/include/configuration/configNagios/formNagios.php(961): updateNagiosInDB('1')
#3 /usr/share/centreon/www/include/configuration/configNagios/nagios.php(83): require_once('/usr/share/cent...')
#4 /usr/share/centreon/www/main.get.php(258): include_once('/usr/share/cent...')
#5 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 275
[10-Feb-2021 02:34:50 Europe/Paris] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'postpone_notification_to_timeperiod' in 'field list' in /usr/share/centreon/www/class/centreonDB.class.php:275
Stack trace:
#0 /usr/share/centreon/www/include/configuration/configNagios/DB-Func.php(2253): CentreonDB->query('UPDATE cfg_nagi...')
#1 /usr/share/centreon/www/include/configuration/configNagios/DB-Func.php(210): updateNagios('1')
#2 /usr/share/centreon/www/include/configuration/configNagios/formNagios.php(961): updateNagiosInDB('1')
#3 /usr/share/centreon/www/include/configuration/configNagios/nagios.php(83): require_once('/usr/share/cent...')
#4 /usr/share/centreon/www/main.get.php(258): include_once('/usr/share/cent...')
#5 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 275
[10-Feb-2021 02:35:03 Europe/Paris] [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /centreon/api/beta/auto-discovery/scheduling/jobs"" at /usr/share/centreon/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136

[10-Feb-2021 02:36:03 Europe/Paris] [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /centreon/api/beta/auto-discovery/scheduling/jobs"" at /usr/share/centreon/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136

[10-Feb-2021 02:37:03 Europe/Paris] [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /centreon/api/beta/auto-discovery/scheduling/jobs"" at /usr/share/centreon/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136
```

**Comment by lonnylippold** [comment]
Unable to generate configuration files on 
Centreon 20.10.5 as well please assign and fix

**Comment by Sims24** [comment]
Hi @lonnylippold

This is not an issue related to centreon-engine. Please close and open in the right github https://github.com/centreon/centreon. 

I think you had some troubles with your upgrade. Please refer to the documentation to make sure your database schema is compatible with your components (engine, broker, web, ...)
